services:
  web:
    build: ./webapp
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=demo
      - DATABASE_USER=demo_user
      - DATABASE_PASSWORD=demo_password
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: sql-injection-attack-demo-db
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
    volumes:
      - ./webapp/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5432:5432"

